---
title: "Chapter 2: Discrete random variables"
output: html_notebook
---


# Binomial Distribution 

* A binomial experiment consists of a fixed number of $n$ trials. 
* Each trial has two possible outcomes: success, failure. 
* The probability of success is denoted by $p,\:0\leq p\leq 1$.
* The probability of failure is $1-p$. 
* The trials are assumed independent:
* the outcome of one trial does not affect the  outcome probability of any other trial.


```{r}
n=10  # Sample size
p=.5 # probability of success 
x=0:n  # Possible values
round(dbinom(x,n,p),4)

choose(10,6)

210*(0.5)^4*(0.5)^6

.8^10
dbinom(0,10,0.2)

45*(.2)^2*(.8)^8
choose(10,2)*(.2)^2*(.8)^8
dbinom(2,10,.2)
sum(dbinom(0:4,10,.2))
pbinom(4,10,.2)
library(formattable)
dbinom(2,10,.2)
percent(dbinom(2,10,.2))






```


```{r}
B<-as.table(dbinom(0:10,10,.2))
B
names(B)<-0:10
B
plot(B,col="red",main="Bar plot for binomial PDF",xlab="Number of correct answers",ylab="Probability")
```
```{r}
set.seed(123)
res<-rbinom(10000,10,.2)
head(res,10)
mean(res)
round(dbinom(0:10,10,.2),4)
table(res)
sum((0:10)*dbinom(0:10,10,.2))
(0:10)%*%dbinom(0:10,10,.2)

var(res)

mean((res-mean(res))^2)
(0:10-2)^2%*%dbinom(0:10,10,.2)
10*.2*.8
```

